add_newline = true
scan_timeout = 0

format = """
$directory\
$git_branch\
$git_status\
$kubernetes\
$aws\
$all
"""

[aws]
format = "[âœ](bold white) [$symbol$profile]($style) "
style = "bold blue"
symbol = "â˜ï¸ "

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 500
format = "time [$duration](bold yellow)"

[container]
format = "[$symbol \\[$name\\]]($style) "
disabled = true

[directory]
truncation_length = 8
format = "[$path]($style) "
style  = "bold #50fa7b"

[docker_context]
disabled = true

[git_status]
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"

[git_branch]
symbol = "[âœ](bold white) "
format= "[$symbol$branch]($style) "

[git_commit]
commit_hash_length = 4
style = "bold green"
tag_symbol = "ğŸ· "

[kubernetes]
disabled = false
format = '[[âœ](bold white) $context\($namespace\)](bold cyan) '

[helm]
disabled = false
format = "via[ âˆ$version ](bold white)"

[python]
symbol = "î˜† "
pyenv_version_name = true
pyenv_prefix = "python "
format = '[${symbol}(${version} )(\($virtualenv\))]($style)'

[nodejs]
symbol = "ï¢˜ "
format = "[$symbol$version]($style) "
style = "#abdbe3"
detect_files = ["package.json", ".node-version", ".nvrc"]

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = true

[php]
disabled = true

[username]
disabled = true

[package]
disabled = true

[vagrant]
disabled = true

[gcloud]
disabled = true