add_newline = true
scan_timeout = 0

[aws]
format = 'on [$symbol ( $profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "â˜ï¸ "

[battery]
charging_symbol    = "âš¡ï¸ "
discharging_symbol = "â˜ ï¸  "
full_symbol        = "ğŸ”‹ "
unknown_symbol     = "ğŸ¤¨ "

[[battery.display]]
threshold = 15
style     = "bold red"

[[battery.display]]
threshold = 30
style     = "bold yellow"

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 500
format = "time [$duration](bold yellow)"

[container]
format = "[$symbol \\[$name\\]]($style) "
disabled = true

[directory]
truncation_symbol = "â—€ï¸ .."
truncation_length = 2
truncate_to_repo = true
format = "[$path]($style)( [$read_only]($read_only_style)) "
read_only = "ğŸš§"

[docker_context]
symbol = "ğŸ³ "

[git_status]
format = '([$all_status$ahead_behind]($style)) '
conflicted = "âŒ"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
stashed = "ğŸš«"
renamed = "â˜‘ï¸"
deleted = "â›”"
ahead = "â‡¡${count}"
behind = "â‡£${count}"

[git_branch]
symbol = "ğŸƒ "
format= "[$symbol$branch]($style) "

[git_commit]
commit_hash_length = 4
style = "bold green"
tag_symbol = "ğŸ· "

[kubernetes]
symbol = "â˜¸ï¸  "
format = '[$symbol$context\($namespace\)]($style)'
style = "#c5f542"
disabled = false

[helm]
disabled = false
format = "via[ âˆ$version ](bold white)"

[python]
symbol = "î˜† "
pyenv_version_name = true
pyenv_prefix = "python "
format = '[${symbol}(${version} )(\($virtualenv\))]($style)'

[nodejs]
symbol = "ï¢˜ "
format = "[$symbol$version]($style) "
style = "#abdbe3"
detect_files = ["package.json", ".node-version", ".nvrc"]

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = true

[php]
format = "via [ğŸ”¹ $version](147 bold) "

[username]
disabled = true

[package]
disabled = true

[vagrant]
disabled = true

[gcloud]
disabled = true